# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Adam\Google Drive\Scripts\atomicTextureFileManager\UIs\atomic_TFM_UI.ui'
#
# Created: Thu Nov 10 01:11:15 2016
#      by: pyside-uic 0.2.14 running on PySide 1.2.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1293, 1012)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.filesTab = QtGui.QWidget()
        self.filesTab.setObjectName("filesTab")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.filesTab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.existingTextureLabel = QtGui.QLabel(self.filesTab)
        self.existingTextureLabel.setObjectName("existingTextureLabel")
        self.verticalLayout.addWidget(self.existingTextureLabel)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.colorKeyCurrent = QtGui.QLabel(self.filesTab)
        self.colorKeyCurrent.setObjectName("colorKeyCurrent")
        self.horizontalLayout.addWidget(self.colorKeyCurrent)
        self.colorKeyMissing = QtGui.QLabel(self.filesTab)
        self.colorKeyMissing.setObjectName("colorKeyMissing")
        self.horizontalLayout.addWidget(self.colorKeyMissing)
        spacerItem = QtGui.QSpacerItem(0, 0, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.existingTextureList = QtGui.QTableWidget(self.filesTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.existingTextureList.sizePolicy().hasHeightForWidth())
        self.existingTextureList.setSizePolicy(sizePolicy)
        self.existingTextureList.setDragEnabled(True)
        self.existingTextureList.setDragDropMode(QtGui.QAbstractItemView.DragOnly)
        self.existingTextureList.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.existingTextureList.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.existingTextureList.setObjectName("existingTextureList")
        self.existingTextureList.setColumnCount(4)
        self.existingTextureList.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.existingTextureList.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.existingTextureList.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.existingTextureList.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.existingTextureList.setHorizontalHeaderItem(3, item)
        self.existingTextureList.horizontalHeader().setDefaultSectionSize(200)
        self.existingTextureList.horizontalHeader().setMinimumSectionSize(90)
        self.existingTextureList.horizontalHeader().setStretchLastSection(True)
        self.existingTextureList.verticalHeader().setCascadingSectionResizes(True)
        self.existingTextureList.verticalHeader().setDefaultSectionSize(30)
        self.verticalLayout.addWidget(self.existingTextureList)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.nodeTypesLabel = QtGui.QLabel(self.filesTab)
        self.nodeTypesLabel.setObjectName("nodeTypesLabel")
        self.horizontalLayout_4.addWidget(self.nodeTypesLabel)
        self.selectAllNodeTypes = QtGui.QCheckBox(self.filesTab)
        self.selectAllNodeTypes.setChecked(False)
        self.selectAllNodeTypes.setObjectName("selectAllNodeTypes")
        self.horizontalLayout_4.addWidget(self.selectAllNodeTypes)
        self.selectTextureNodesOnly = QtGui.QCheckBox(self.filesTab)
        self.selectTextureNodesOnly.setChecked(True)
        self.selectTextureNodesOnly.setObjectName("selectTextureNodesOnly")
        self.horizontalLayout_4.addWidget(self.selectTextureNodesOnly)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.defaultFolderTypes = QtGui.QTableWidget(self.filesTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.defaultFolderTypes.sizePolicy().hasHeightForWidth())
        self.defaultFolderTypes.setSizePolicy(sizePolicy)
        self.defaultFolderTypes.setAutoFillBackground(False)
        self.defaultFolderTypes.setObjectName("defaultFolderTypes")
        self.defaultFolderTypes.setColumnCount(2)
        self.defaultFolderTypes.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.defaultFolderTypes.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.defaultFolderTypes.setHorizontalHeaderItem(1, item)
        self.defaultFolderTypes.horizontalHeader().setCascadingSectionResizes(False)
        self.defaultFolderTypes.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.defaultFolderTypes)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.keepOriginalSubfolders = QtGui.QCheckBox(self.filesTab)
        self.keepOriginalSubfolders.setChecked(True)
        self.keepOriginalSubfolders.setObjectName("keepOriginalSubfolders")
        self.horizontalLayout_2.addWidget(self.keepOriginalSubfolders)
        self.updatePath = QtGui.QCheckBox(self.filesTab)
        self.updatePath.setChecked(True)
        self.updatePath.setObjectName("updatePath")
        self.horizontalLayout_2.addWidget(self.updatePath)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.actionButtonsLayout = QtGui.QHBoxLayout()
        self.actionButtonsLayout.setObjectName("actionButtonsLayout")
        self.copy = QtGui.QPushButton(self.filesTab)
        self.copy.setObjectName("copy")
        self.actionButtonsLayout.addWidget(self.copy)
        self.move = QtGui.QPushButton(self.filesTab)
        self.move.setObjectName("move")
        self.actionButtonsLayout.addWidget(self.move)
        self.search = QtGui.QPushButton(self.filesTab)
        self.search.setObjectName("search")
        self.actionButtonsLayout.addWidget(self.search)
        self.refresh = QtGui.QPushButton(self.filesTab)
        self.refresh.setObjectName("refresh")
        self.actionButtonsLayout.addWidget(self.refresh)
        self.cancel = QtGui.QPushButton(self.filesTab)
        self.cancel.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.cancel.setObjectName("cancel")
        self.actionButtonsLayout.addWidget(self.cancel)
        self.verticalLayout.addLayout(self.actionButtonsLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.filesTab, "")
        self.toolsTab = QtGui.QWidget()
        self.toolsTab.setObjectName("toolsTab")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.toolsTab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toolBox = QtGui.QToolBox(self.toolsTab)
        self.toolBox.setObjectName("toolBox")
        self.imageResizeReformat = QtGui.QWidget()
        self.imageResizeReformat.setGeometry(QtCore.QRect(0, 0, 1235, 812))
        self.imageResizeReformat.setObjectName("imageResizeReformat")
        self.toolBox.addItem(self.imageResizeReformat, "")
        self.uvTilingSetup = QtGui.QWidget()
        self.uvTilingSetup.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.uvTilingSetup.setObjectName("uvTilingSetup")
        self.toolBox.addItem(self.uvTilingSetup, "")
        self.makePathsRelative = QtGui.QWidget()
        self.makePathsRelative.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.makePathsRelative.setObjectName("makePathsRelative")
        self.toolBox.addItem(self.makePathsRelative, "")
        self.verticalLayout_4.addWidget(self.toolBox)
        self.tabWidget.addTab(self.toolsTab, "")
        self.settingsTab = QtGui.QWidget()
        self.settingsTab.setObjectName("settingsTab")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.settingsTab)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.settingsLabel = QtGui.QLabel(self.settingsTab)
        self.settingsLabel.setWordWrap(True)
        self.settingsLabel.setObjectName("settingsLabel")
        self.verticalLayout_7.addWidget(self.settingsLabel)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.xmlLabel = QtGui.QLabel(self.settingsTab)
        self.xmlLabel.setEnabled(True)
        self.xmlLabel.setInputMethodHints(QtCore.Qt.ImhNone)
        self.xmlLabel.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.xmlLabel.setObjectName("xmlLabel")
        self.verticalLayout_6.addWidget(self.xmlLabel)
        self.xmlLocation = QtGui.QLineEdit(self.settingsTab)
        self.xmlLocation.setEnabled(False)
        self.xmlLocation.setObjectName("xmlLocation")
        self.verticalLayout_6.addWidget(self.xmlLocation)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.nodeTypesList = QtGui.QTableWidget(self.settingsTab)
        self.nodeTypesList.setMinimumSize(QtCore.QSize(0, 0))
        self.nodeTypesList.setSizeIncrement(QtCore.QSize(0, 0))
        self.nodeTypesList.setRowCount(0)
        self.nodeTypesList.setColumnCount(4)
        self.nodeTypesList.setObjectName("nodeTypesList")
        self.nodeTypesList.setColumnCount(4)
        self.nodeTypesList.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.nodeTypesList.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.nodeTypesList.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.nodeTypesList.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.nodeTypesList.setHorizontalHeaderItem(3, item)
        self.nodeTypesList.horizontalHeader().setCascadingSectionResizes(False)
        self.nodeTypesList.horizontalHeader().setDefaultSectionSize(200)
        self.nodeTypesList.horizontalHeader().setMinimumSectionSize(200)
        self.nodeTypesList.horizontalHeader().setSortIndicatorShown(False)
        self.nodeTypesList.horizontalHeader().setStretchLastSection(True)
        self.nodeTypesList.verticalHeader().setCascadingSectionResizes(False)
        self.nodeTypesList.verticalHeader().setHighlightSections(True)
        self.verticalLayout_5.addWidget(self.nodeTypesList)
        self.acceptedNodesLabel = QtGui.QLabel(self.settingsTab)
        self.acceptedNodesLabel.setObjectName("acceptedNodesLabel")
        self.verticalLayout_5.addWidget(self.acceptedNodesLabel)
        self.manualAddNodesLabel = QtGui.QLabel(self.settingsTab)
        self.manualAddNodesLabel.setObjectName("manualAddNodesLabel")
        self.verticalLayout_5.addWidget(self.manualAddNodesLabel)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.newParameterName = QtGui.QLineEdit(self.settingsTab)
        self.newParameterName.setObjectName("newParameterName")
        self.gridLayout.addWidget(self.newParameterName, 1, 2, 1, 2)
        self.addNodeType = QtGui.QPushButton(self.settingsTab)
        self.addNodeType.setObjectName("addNodeType")
        self.gridLayout.addWidget(self.addNodeType, 2, 3, 1, 1)
        self.autoAddNodeButton = QtGui.QPushButton(self.settingsTab)
        self.autoAddNodeButton.setObjectName("autoAddNodeButton")
        self.gridLayout.addWidget(self.autoAddNodeButton, 5, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 3, 3, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(300, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 5, 2, 1, 1)
        self.nodeTypeLabel = QtGui.QLabel(self.settingsTab)
        self.nodeTypeLabel.setObjectName("nodeTypeLabel")
        self.gridLayout.addWidget(self.nodeTypeLabel, 0, 0, 1, 1)
        self.parameterNameLabel = QtGui.QLabel(self.settingsTab)
        self.parameterNameLabel.setObjectName("parameterNameLabel")
        self.gridLayout.addWidget(self.parameterNameLabel, 0, 2, 1, 1)
        self.newNodeType = QtGui.QLineEdit(self.settingsTab)
        self.newNodeType.setObjectName("newNodeType")
        self.gridLayout.addWidget(self.newNodeType, 1, 0, 1, 1)
        self.autoAddNodeLabel = QtGui.QLabel(self.settingsTab)
        self.autoAddNodeLabel.setObjectName("autoAddNodeLabel")
        self.gridLayout.addWidget(self.autoAddNodeLabel, 4, 0, 1, 1)
        self.defaultFolderLabel = QtGui.QLabel(self.settingsTab)
        self.defaultFolderLabel.setObjectName("defaultFolderLabel")
        self.gridLayout.addWidget(self.defaultFolderLabel, 0, 1, 1, 1)
        self.defaultFolder = QtGui.QComboBox(self.settingsTab)
        self.defaultFolder.setMinimumSize(QtCore.QSize(250, 0))
        self.defaultFolder.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.defaultFolder.setObjectName("defaultFolder")
        self.gridLayout.addWidget(self.defaultFolder, 1, 1, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.settingsTab, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.xmlLabel.setBuddy(self.xmlLocation)
        self.acceptedNodesLabel.setBuddy(self.nodeTypesList)
        self.nodeTypeLabel.setBuddy(self.newNodeType)
        self.parameterNameLabel.setBuddy(self.newParameterName)
        self.autoAddNodeLabel.setBuddy(self.autoAddNodeButton)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.existingTextureLabel.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Scene Files</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.colorKeyCurrent.setText(QtGui.QApplication.translate("MainWindow", "Currently in Project   ", None, QtGui.QApplication.UnicodeUTF8))
        self.colorKeyMissing.setText(QtGui.QApplication.translate("MainWindow", "   Missing Files   ", None, QtGui.QApplication.UnicodeUTF8))
        self.existingTextureList.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.existingTextureList.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Node Type", None, QtGui.QApplication.UnicodeUTF8))
        self.existingTextureList.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "Default Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.existingTextureList.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "Path", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeTypesLabel.setText(QtGui.QApplication.translate("MainWindow", "File Types by Default Project Folder Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.selectAllNodeTypes.setText(QtGui.QApplication.translate("MainWindow", "Select All Node Types", None, QtGui.QApplication.UnicodeUTF8))
        self.selectTextureNodesOnly.setText(QtGui.QApplication.translate("MainWindow", "Texture Files Only", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultFolderTypes.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultFolderTypes.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.keepOriginalSubfolders.setToolTip(QtGui.QApplication.translate("MainWindow", "If the original file location is in a subfolder of a different sourceimages folder, and you want to keep that folder structure, make sure this is checked.", None, QtGui.QApplication.UnicodeUTF8))
        self.keepOriginalSubfolders.setStatusTip(QtGui.QApplication.translate("MainWindow", "Check to keep original sub-folder structure", None, QtGui.QApplication.UnicodeUTF8))
        self.keepOriginalSubfolders.setText(QtGui.QApplication.translate("MainWindow", "Keep Original Subfolders", None, QtGui.QApplication.UnicodeUTF8))
        self.updatePath.setToolTip(QtGui.QApplication.translate("MainWindow", "When this is checked, the nodes in the scene will be updated to the copied/moved path", None, QtGui.QApplication.UnicodeUTF8))
        self.updatePath.setStatusTip(QtGui.QApplication.translate("MainWindow", "Uncheck if you want to copy the file to source images, but want to keep the original file location on the node.", None, QtGui.QApplication.UnicodeUTF8))
        self.updatePath.setText(QtGui.QApplication.translate("MainWindow", "Update Path on Run", None, QtGui.QApplication.UnicodeUTF8))
        self.copy.setText(QtGui.QApplication.translate("MainWindow", "Copy Misplaced Files", None, QtGui.QApplication.UnicodeUTF8))
        self.move.setText(QtGui.QApplication.translate("MainWindow", "Move Misplaced Files", None, QtGui.QApplication.UnicodeUTF8))
        self.search.setText(QtGui.QApplication.translate("MainWindow", "Attempt File Search", None, QtGui.QApplication.UnicodeUTF8))
        self.refresh.setText(QtGui.QApplication.translate("MainWindow", "Refresh Scene Files List", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.filesTab), QtGui.QApplication.translate("MainWindow", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.imageResizeReformat), QtGui.QApplication.translate("MainWindow", "Image Resize/Reformat", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.uvTilingSetup), QtGui.QApplication.translate("MainWindow", "UV Tiling Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.makePathsRelative), QtGui.QApplication.translate("MainWindow", "Make All Paths Relative", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemToolTip(self.toolBox.indexOf(self.makePathsRelative), QtGui.QApplication.translate("MainWindow", "Convert absolute paths to relative paths", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.toolsTab), QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.settingsLabel.setText(QtGui.QApplication.translate("MainWindow", "USE WITH CAUTION!!\n"
"\n"
"These settings will affect the way this tool runs!  It was designed to be expandable, and uses an xml document to keep a list of acceptable image types.  Some are inserted by default, but the list can be expanded upon by you.\n"
"It is important to understand that changing this list will directly affect this tool\'s ability to preform.  Make sure you understand what you are doing before you hit save!", None, QtGui.QApplication.UnicodeUTF8))
        self.xmlLabel.setText(QtGui.QApplication.translate("MainWindow", "XML File Location", None, QtGui.QApplication.UnicodeUTF8))
        self.xmlLocation.setToolTip(QtGui.QApplication.translate("MainWindow", "The XML file that maintains the list of texture file node types", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeTypesList.setToolTip(QtGui.QApplication.translate("MainWindow", "List of excepted file nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeTypesList.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeTypesList.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "nodeType", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeTypesList.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "defaultFolder", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeTypesList.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "parameterName", None, QtGui.QApplication.UnicodeUTF8))
        self.acceptedNodesLabel.setText(QtGui.QApplication.translate("MainWindow", "Accepted Nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.manualAddNodesLabel.setText(QtGui.QApplication.translate("MainWindow", "Manually add new node", None, QtGui.QApplication.UnicodeUTF8))
        self.addNodeType.setText(QtGui.QApplication.translate("MainWindow", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.autoAddNodeButton.setToolTip(QtGui.QApplication.translate("MainWindow", "This will bring up a list of attribues from the existing node.  Pick the correct parameter from there", None, QtGui.QApplication.UnicodeUTF8))
        self.autoAddNodeButton.setText(QtGui.QApplication.translate("MainWindow", "   Auto Add From Selection   ", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeTypeLabel.setText(QtGui.QApplication.translate("MainWindow", "nodeType", None, QtGui.QApplication.UnicodeUTF8))
        self.parameterNameLabel.setText(QtGui.QApplication.translate("MainWindow", "parameterName", None, QtGui.QApplication.UnicodeUTF8))
        self.autoAddNodeLabel.setText(QtGui.QApplication.translate("MainWindow", "Get the node type and attribute from the currently selected node", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultFolderLabel.setText(QtGui.QApplication.translate("MainWindow", "defaultFolder", None, QtGui.QApplication.UnicodeUTF8))
        self.defaultFolder.setToolTip(QtGui.QApplication.translate("MainWindow", "Based on Project Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settingsTab), QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))

